/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.redesocial_livros.view;

import br.com.redesocial_livros.dto.UsuarioDTO;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Barbara
 */
public class PrincipalVIEW extends javax.swing.JFrame {

    UsuarioDTO u_dto = new UsuarioDTO();

    /**
     * Creates new form LivrosVIEW
     * @param u_dto
     */
    public PrincipalVIEW(UsuarioDTO u_dto) {
        initComponents();
        this.u_dto = u_dto;
        this.setLocationRelativeTo(null);
    }

    private void sair() {
        Object options[] = {"Sair", "Cancelar"};
        if (JOptionPane.showOptionDialog(null, "DESEJA MESMO SAIR?", "Aviso",
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]) == 0) {
            System.exit(0);
        }
    }

    private void abreLivroView() {
        LivroVIEW livroVIEW = new LivroVIEW();
        this.desktopPane.add(livroVIEW);
        livroVIEW.setVisible(true);
        livroVIEW.setPosition();
    }

    private void abreAutorView() {
        AutorVIEW autorVIEW = new AutorVIEW();
        this.desktopPane.add(autorVIEW);
        autorVIEW.setVisible(true);
        autorVIEW.setPosition();
    }

    private void abreAvaliarView() {
        AvaliarVIEW avaliarVIEW = new AvaliarVIEW(u_dto);
        this.desktopPane.add(avaliarVIEW);
        avaliarVIEW.setVisible(true);
        avaliarVIEW.setPosition();
    }

    private void abreVerTodas() {
        VerTodasAvaliacoesVIEW vtaVIEW = new VerTodasAvaliacoesVIEW();
        this.desktopPane.add(vtaVIEW);
        vtaVIEW.setVisible(true);
        vtaVIEW.setPosition();
    }

    private void abreDados(){
        AlterarDadosVIEW adVIEW = new AlterarDadosVIEW(u_dto, this);
        this.desktopPane.add(adVIEW);
        adVIEW.setVisible(true);
        adVIEW.setPosition();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon imageicon = new ImageIcon(getClass().getResource("imagens/foto-projeto-livros.png"));
        Image image = imageicon.getImage();
        desktopPane = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics graphics){
                graphics.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
        }
        ;
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        menuLivros = new javax.swing.JMenu();
        itemMenuAutor = new javax.swing.JMenuItem();
        itemMenuLivro = new javax.swing.JMenuItem();
        itemMenuAvaliar = new javax.swing.JMenuItem();
        menuSocial = new javax.swing.JMenu();
        itemMenuVerTodas = new javax.swing.JMenuItem();
        menuMinhaConta = new javax.swing.JMenu();
        itemMenuDados = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        menuLivros.setMnemonic('e');
        menuLivros.setText("Cadastro");

        itemMenuAutor.setText("Autor");
        itemMenuAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAutorActionPerformed(evt);
            }
        });
        menuLivros.add(itemMenuAutor);

        itemMenuLivro.setMnemonic('y');
        itemMenuLivro.setText("Livro");
        itemMenuLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuLivroActionPerformed(evt);
            }
        });
        menuLivros.add(itemMenuLivro);

        itemMenuAvaliar.setText("Avaliar Livro");
        itemMenuAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAvaliarActionPerformed(evt);
            }
        });
        menuLivros.add(itemMenuAvaliar);

        menuBar.add(menuLivros);

        menuSocial.setMnemonic('e');
        menuSocial.setText("Social");

        itemMenuVerTodas.setText("Ver Outras Avaliações");
        itemMenuVerTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuVerTodasActionPerformed(evt);
            }
        });
        menuSocial.add(itemMenuVerTodas);

        menuBar.add(menuSocial);

        menuMinhaConta.setMnemonic('e');
        menuMinhaConta.setText("Minha Conta");

        itemMenuDados.setText("Meus Dados");
        itemMenuDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuDadosActionPerformed(evt);
            }
        });
        menuMinhaConta.add(itemMenuDados);

        menuBar.add(menuMinhaConta);

        menuSair.setMnemonic('h');
        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        menuBar.add(menuSair);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        sair();
    }//GEN-LAST:event_menuSairMouseClicked

    private void itemMenuLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuLivroActionPerformed
        abreLivroView();
    }//GEN-LAST:event_itemMenuLivroActionPerformed

    private void itemMenuAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAutorActionPerformed
        abreAutorView();
    }//GEN-LAST:event_itemMenuAutorActionPerformed

    private void itemMenuAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAvaliarActionPerformed
        abreAvaliarView();
    }//GEN-LAST:event_itemMenuAvaliarActionPerformed

    private void itemMenuVerTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuVerTodasActionPerformed
        abreVerTodas();
    }//GEN-LAST:event_itemMenuVerTodasActionPerformed

    private void itemMenuDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuDadosActionPerformed
        abreDados();
    }//GEN-LAST:event_itemMenuDadosActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PrincipalVIEW().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem itemMenuAutor;
    private javax.swing.JMenuItem itemMenuAvaliar;
    private javax.swing.JMenuItem itemMenuDados;
    private javax.swing.JMenuItem itemMenuLivro;
    private javax.swing.JMenuItem itemMenuVerTodas;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuLivros;
    private javax.swing.JMenu menuMinhaConta;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuSocial;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
