/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.redesocial_livros.view;

;

import br.com.redesocial_livros.ctr.AvaliarCTR;
import br.com.redesocial_livros.ctr.LivroCTR;
import br.com.redesocial_livros.ctr.UsuarioCTR;
import br.com.redesocial_livros.dto.AvaliarDTO;
import br.com.redesocial_livros.dto.LivroDTO;
import br.com.redesocial_livros.dto.UsuarioDTO;
import java.awt.Dimension;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Barbara
 */


public class VerTodasAvaliacoesVIEW extends javax.swing.JInternalFrame {

    LivroDTO l_dto = new LivroDTO();
    LivroCTR l_ctr = new LivroCTR();
    UsuarioDTO u_dto = new UsuarioDTO();
    UsuarioCTR u_ctr = new UsuarioCTR();
    AvaliarDTO av_dto = new AvaliarDTO();
    AvaliarCTR av_ctr = new AvaliarCTR();
    ResultSet rs;
    DefaultTableModel tabela_consulta;

    /**
     * Creates new form VerTodasAvaliacoes
     */
    public VerTodasAvaliacoesVIEW() {
        initComponents();
        tabela_consulta = (DefaultTableModel) jtl_tabela.getModel();
    }

    public void setPosition() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    private void preencheTabela(String titulo) {
        try {
            tabela_consulta.setNumRows(0);
            l_dto.setTitulo(titulo);
            rs = av_ctr.consultar(u_dto, l_dto, 3);

            while (rs.next()) {
                tabela_consulta.addRow(new Object[]{
                    rs.getInt("id_usuario"), //invisivel
                    rs.getString("usuario_nome"),
                    rs.getInt("id_livro"), //invisivel
                    rs.getString("titulo"),
                    rs.getString("autor_nome")
                });
            }
        } catch (Exception e) {
            System.out.println("ERRO NA TABELA: " + e.getMessage());
        } finally {
            av_ctr.CloseDB();
        }
    }

    private void limpaCampos() {
        nome_usuario.setText("");
        nome_livro.setText("");
        avaliacao.setText("");
    }

        private void preencheCampos(int id_usuario, int id_livro) {
            try {
                u_dto.setId_usuario(id_usuario);
                l_dto.setId_livro(id_livro);
                rs = av_ctr.consultar(u_dto, l_dto, 2);
                while (rs.next()) {
                    nome_usuario.setText(rs.getString("usuario_nome"));
                    nome_livro.setText(rs.getString("titulo"));
                    avaliacao.setText(rs.getString("comentario"));
                }
            } catch (Exception e) {
                System.out.println("Erro SQL: " + e.getMessage());
            } finally {
                av_ctr.CloseDB();
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pesquisa_titulo = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtl_tabela = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        nome_usuario = new javax.swing.JLabel();
        nome_livro = new javax.swing.JLabel();
        avaliacao = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();

        jLabel1.setText("Pesquisar por nome do livro:");

        btnPesquisar.setText("OK");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("VER AVALIAÇÕES DE OUTROS USUÁRIOS");

        jtl_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdUser", "Usuário", "", "Livro", "Autor"
            }
        ));
        jtl_tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtl_tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtl_tabela);
        if (jtl_tabela.getColumnModel().getColumnCount() > 0) {
            jtl_tabela.getColumnModel().getColumn(0).setMinWidth(0);
            jtl_tabela.getColumnModel().getColumn(0).setPreferredWidth(0);
            jtl_tabela.getColumnModel().getColumn(0).setMaxWidth(0);
            jtl_tabela.getColumnModel().getColumn(2).setMinWidth(0);
            jtl_tabela.getColumnModel().getColumn(2).setPreferredWidth(0);
            jtl_tabela.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Avaliação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        nome_usuario.setText("...");

        nome_livro.setText("...");

        avaliacao.setText("...");

        jLabel3.setText("Usuário:");

        jLabel4.setText("Livro:");

        jLabel5.setText("Comentários sobre o livro:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nome_usuario)
                    .addComponent(nome_livro)
                    .addComponent(avaliacao)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nome_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(nome_livro)
                .addGap(53, 53, 53)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(avaliacao)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pesquisa_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPesquisar)))
                                .addGap(43, 43, 43)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(btnSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesquisa_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisar))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        preencheTabela(pesquisa_titulo.getText());
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void jtl_tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtl_tabelaMouseClicked
        int id_usuario = Integer.parseInt(String.valueOf(jtl_tabela.getValueAt(jtl_tabela.getSelectedRow(), 0))); // id_usuario (invisível)
        int id_livro = Integer.parseInt(String.valueOf(jtl_tabela.getValueAt(jtl_tabela.getSelectedRow(), 2)));   // id_livro (invisível)
        limpaCampos();
        preencheCampos(id_usuario, id_livro);
    }//GEN-LAST:event_jtl_tabelaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avaliacao;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtl_tabela;
    private javax.swing.JLabel nome_livro;
    private javax.swing.JLabel nome_usuario;
    private javax.swing.JTextField pesquisa_titulo;
    // End of variables declaration//GEN-END:variables
}
